config/routes.rb
CarAuctionSite::Application.routes.draw do
  get "auctionheroku/apps"

  resources :cars do 
    collection do
      post :auction_save
    end
  end
  root :to => 'cars#index'  
  match 'sessions/delete' => 'sessions#destroy'
  resources :users
  resources :sessions

  match ':controller(/:action(/:id))(.:format)'
end

app/models/auction.rb
class Auction < ActiveRecord::Base
  belongs_to :cars
end

app/models/car.rb
class Car < ActiveRecord::Base
  has_many :auctions
  has_attached_file :photo,
                  :url  => "/assets/products/:id/:style/:basename.:extension",
                  :path => ":rails_root/public/assets/products/:id/:style/:basename.:extension"

validates_attachment_presence :photo
validates_attachment_size :photo, :less_than => 5.megabytes
validates_attachment_content_type :photo, :content_type => ['image/jpeg', 'image/png']
end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :email, :password, :password_confirmation  
  has_secure_password  
  validates_presence_of :password, :on => :create    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery  
  
  private  
  
  def current_user  
    @current_user ||= User.find(session[:user_id]) if session[:user_id]  
  end  
  
  helper_method :current_user 
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  # GET /cars
  # GET /cars.json
  #http_basic_authenticate_with :name => "frodo", :password => "thering"
  def index
    @cars = Car.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @cars }
    end
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
    @car = Car.find(params[:id])    
    @auction = Auction.new
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/new
  # GET /cars/new.json
  def new
    @car = Car.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @car }
    end
  end

  # GET /cars/1/edit
  def edit
    @car = Car.find(params[:id])
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new
    @car.name = params['car']['name']
    @car.description = params['car']['description']    
    @car.starting_price = params['car']['starting_price']
    @car.current_bid_amount = params['car']['starting_price']
    response["chunked"] = true
    @car.photo = params['car']['photo']
    
    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render json: @car, status: :created, location: @car }
      else
        format.html { render action: "new" }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /cars/1
  # PUT /cars/1.json
  def update
    if(params[:auction])
      @auction = Auction.new(params[:auction])
      @car = Car.find(params[:auction][:car_id])
      @car.raise_amount = params[:auction][:raise_amount]
      @car.current_bid_amount += params[:auction][:raise_amount].to_i
      if @auction.save
        if @car.save
          respond_to do |format|
            format.js
          end
        end
      end
    else
      @car = Car.find(params[:id])
      @car.current_bid_amount = params['car']['starting_price']  
      respond_to do |format|
        if @car.update_attributes(params[:car])
          format.html { redirect_to @car, notice: 'Car was successfully updated.' }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @car.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  
  def auction_save
    @auction = Auction.new(params[:auction])
    @car = Car.find(params[:auction][:car_id])
    @car.raise_amount = params[:auction][:raise_amount]
    @car.current_bid_amount += params[:auction][:raise_amount].to_i
    if @auction.save
      @car.save
      respond_to do |format|
        format.js
      end
      #respond_to auction_save.js.erb
    #render :text => "Successfully Completed."
    end    
  end  
  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car = Car.find(params[:id])
    @car.destroy

    respond_to do |format|
      format.html { redirect_to cars_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new  
  end  
  
  def create  
      user = User.find_by_email(params[:email])  
      if user && user.authenticate(params[:password])  
        session[:user_id] = user.id  
        redirect_to root_url, :notice => "Logged in!"  
      else  
        flash.now.alert = "Invalid email or password"  
        render "new"  
      end  
    end   
  
  def destroy  
    session[:user_id] = nil  
    redirect_to root_url, :notice => "Logged out!"  
  end  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new  
    @user = User.new  
  end  
  
  def create  
    @user = User.new(params[:user])  
    if @user.save  
      session[:user_id] = @user.id
      redirect_to root_url, :notice => "Signed up!"  
    else  
      render "new"  
    end  
  end  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cars/ auction_save.js.erb
$('#success_div').html("Saved Successfully.")

app/views/cars/_form.html.erb
<div class='span7 offset2 container'>
<%= form_for(@car, :html => { :multipart => true, :class => 'well' } ) do |f| %>
  <% if @car.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@car.errors.count, "error") %> prohibited this car from being saved:</h2>

      <ul>
      <% @car.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class='thumbnail'>
  	<%=image_tag @car.photo.url,:size =>'450x350' %>
  <div class='pull_right' align='right'>
  	<%=link_to 'change pic','#', :onclick => '$("#photo_field").show()' %></div>
  </div>
    <div class="field" style='display:none' id='photo_field' align='right'>    
    <%= f.file_field :photo %>
  </div>
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description, :rows => '25' %>
  </div>
  <div class="field">
    <%= f.label :starting_price %>
    <%= f.text_field :starting_price %>
  </div>
  <div class="field">
    <%= f.label :end_date %>
    <%= f.date_select :end_date %>
  </div>  

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/cars/auction_save.js.erb
$('#success_div').html("Saved Successfully.");
$('#current_bid_amount').html('<%= escape_javascript @car.current_bid_amount.to_s %>');

app/views/cars/edit.html.erb
<h1>Editing car</h1>

<%= render 'form' %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.haml
:css
  .hero-unit{
    background-image :url('/assets/Toyota-Avanza-wallpaper-03.jpg');  
  }
.hero-unit
  %center    
    %p
      /=link_to image_tag('facebook_btn.png'), "#"
.container{:style => 'border:1px solid #000;'}
  .row
    - i = 0
    - @cars.each do |car|
      .span3{:style => "height:400px;margin-top:15px"}
        %a{:href => '/cars/'+car.id.to_s, :class => 'thickbox '}
          .thumbnail   
            = image_tag(car.photo.url, :size => "244x180")            
        %h6{:style => "font-weight:normal; padding: 10px 20px 0px 20px; font-weight: bold"} 
          = car.name
        %h4{:style => "padding: 0px 20px 10px 20px;"}
          %a{:href => '/guides/display?height=600&width=800&id=', :class=>'thickbox'}
            = car.starting_price
        %p{:style => "padding-left: 20px; font-style:oblique;"} 
          = car.description
        %p{:style => "padding-left: 20px; color: #666666;"}
          = car.end_date
        %p{:style => "padding-left: 20px; color: #666666;"}
          = car.raise_amount
          = link_to 'Show', car
          /= link_to 'Add to New Guide', new_guide_path
        %p
          = link_to 'Edit', edit_car_path(car)
          = link_to 'Destroy', car, confirm: 'Are you sure?', method: :delete
      - i += 1
      - if i%4 == 0
        %br
     









%br/ 
.footer.modal-footer{:style =>"height:10px;clear:both;position:fixed;bottom:0px;"}
  #fb-root
  .fb-like{"data-send" => "true", "data-show-faces" => "true", "data-width" => "450"}
</script>     
:javascript
  (function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = "//connect.facebook.net/en_GB/all.js#xfbml=1&appId=206096812769730";
      fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));
  $(document).ready(function(){  
      session_id = '#{session[:user_id]}'
      console.log(session_id)
            
  	  
  	  $('#browse_by').change(function(){
  	      addPageHeader();
  	  });
  	  
  	  /* Adding Dynamic Links to the Header */
  	  $('.dynaLink').bind('click',function(event){
             event.preventDefault();
             $.get(this.href,{},function(response){
                     $('#response').html(response)
              }) 
        })
  	  
  });
  
  function changespan(val){
    console.log(val);
    class_val = $('#dynamic-span').attr('class');
    console.log(class_val);
    $('div.'+class_val).each(function(){
      $(this).removeClass();
      $(this).addClass('span'+val)
      
    
    });
  
  }
  
  function addPageHeader(){
            $('#page-header1').empty();
          var token = 'DBHKFSCXVMRTB5HSZD3DU5ZMTZSXYVPIAACZMYJ3OBQ02CH2'
            $.getJSON('https://api.foursquare.com/v2/venues/categories?&oauth_token='+token,{}, function(data) {
        	                    categories = data['response']['categories']
        	                    console.log(data)
        	                    for(i = 0; i<categories.length ; i++){
        	                          $('#page-header1').append('<a   href="#" >'+categories[i]['name']+'</a><nbsp>');
          	                    }
        	  });
 
  	  
  }
  function addPageHeader2(){
          
            $('#page-header1').empty();
          var token = 'DBHKFSCXVMRTB5HSZD3DU5ZMTZSXYVPIAACZMYJ3OBQ02CH2'
  	        $('#page-header1').empty();
            $('#page-header1').append('<h1><a href="#" id="LatestLink" class="dynaLink" onclick="search_guide(\'latest\')">Latest</a>  <a href="#" id="MostPopular" class="dynaLink" onclick="search_guide(\'popular\')"> Most Popular</a>   <a href="#" id="HighestRated" class="dynaLink" onclick="search_guide(\'highrated\')">Highest Rated</a>   <a href="#" id="StressFactor" class="dynaLink" onclick="search_guide(\'stress\')">Stress Factor</a> </h1>')
  	        //addPageHeaderGuide();
  	  
  
  }
  
  function search_guide(key){
      $.ajax({
                               // type : "GET",
                                datatype: 'html',
                                url: 'guides/search?key='+key,

                               /* success: function(data) {
                                $('#content-div').empty();
  								jQuery('#content-div').html(data);
                                },
                                error : function() {
                                         alert("Sorry, The requested property could not be found.");
                                }*/
                        }).done(function( html ) {
                            $("#content-div").html("");
                            $("#content-div").append(html);
                          });
 
  }
          

  

app/views/cars/new.html.erb
<h1>New car</h1>

<%= render 'form' %>

<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>
<div class='container' style='border:0px solid #000;'>
<div class='span7 offset2'>
<div class='well'>
	<div class='thumbnail'><%= image_tag @car.photo.url %></div>

<h4>
  <b>Name:</b>
  <%= @car.name %>
</h4>

<h6>
<p>
  <b>Description:</b>
  <%= @car.description %>
</p>
</h6>

<h6>
	<p>
  <b>Starting price:</b>
  <%= @car.starting_price %>
</p>	
</h6>

<p>
  <b>Current Bid Amount:</b>
  <div id='current_bid_amount'>
  	<%= @car.raise_amount.to_i + @car.starting_price.to_i %>
  </div>
</p>

<p>
  <b>End date:</b>
  <%= @car.end_date %>
</p>

<%=form_for @auction, :remote => true, :url => url_for(:controller => 'cars', :action => 'auction_save'),:format => 'js'  do |f|%>
    			<div style='width:100%;height:auto'>
				Raise Amount:
    			<%= f.text_field :raise_amount,:style => 'width:78px;' %>
				</div>
				<div style='width:100%'>
    			Auction Mail:
    			<%= f.text_field :auction_mail_id,:style => 'width:78px;margin-left:10px;' %>
				<%=f.hidden_field :car_id, :value =>@car.id%>
				</div>
				<div class='button'>
			<%=submit_tag  "Participate", :name => 'auction_save' %></div>
<%end%>
<div id='success_div'></div>
<%if current_user %>
	<%= link_to 'Edit', edit_car_path(@car) %> |
<% end %>
<%= link_to 'Back', cars_path %>
</div>
</div>
</div>


<text type='javascript' > 
  
</text>

app/views/cars/update.js.erb
$('#success_div').html("Saved Successfully.");
$('#current_bid_amount').html('<%= escape_javascript @car.current_bid_amount.to_s %>');

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:charset => "utf-8"}/
    %title Car Auction Site
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %meta{:content => "", :name => "description"}/
    %meta{:content => "", :name => "author"}/  
    = javascript_include_tag 'application'  
    = stylesheet_link_tag 'font-awesome.css', "bootstrap.css", "bootstrap-responsive.css"
    = csrf_meta_tags 
    /= render '_style.css.erb'
    :css
      body {
            
            }
      .hero-unit {
            
            background-repeat:no-repeat;
      }            
  %body
    .navbar.navbar-fixed-top
      .navbar-inner
        .container
          .brand    
            =image_tag( "logo.png", :onclick => "window.location.href = '/'")
          .nav-collapse
            %ul.nav
              %li.active
                - if current_user
                  = link_to "Create Car", new_car_path
            /.nav-collapse
            .btn-group.pull-right
              %li
                - if !current_user
                  =link_to "Signup", "/users/new"
                  =link_to "Login", "/sessions/new"
                -else                  
                  =link_to 'Logout', "/sessions/delete", :method => :delete
    = javascript_include_tag 'jquery-1.7.2.min.js'    
    = yield
    .row
    %hr
      %footer
        %p © 2012 Car Auction Site

app/views/users/new.html.erb
<h1>Sign Up</h1>  
      
    <%= form_for @user do |f| %>  
      <% if @user.errors.any? %>  
        <div class="error_messages">  
          <h2>Form is invalid</h2>  
          <ul>  
            <% for message in @user.errors.full_messages %>  
              <li><%= message %></li>  
            <% end %>  
          </ul>  
        </div>  
      <% end %>  
      <div class="field">  
        <%= f.label :email %>  
        <%= f.text_field :email %>  
      </div>  
      <div class="field">  
        <%= f.label :password %>  
        <%= f.password_field :password %>  
      </div>  
      <div class="field">  
        <%= f.label :password_confirmation %>  
        <%= f.password_field :password_confirmation %>  
      </div>  
      <div class="actions"><%= f.submit %></div>  
    <% end %>  